

export TRANSPARENT="0x00000000"

export BAR_FONT_FAMILY="SF Pro"



export WORKSPACE_ICON_COLOR="0xff4c566a"
export WORKSPACE_ICON_HIGHLIGHT_COLOR="0xff2e3440"
export WORKSPACE_LABEL_COLOR="0xff4c566a"
export WORKSPACE_LABEL_HIGHLIGHT_COLOR="0xff2e3440"
export WORKSPACE_ITEM_BORDER_COLOR="0x60ffffff"
export WORKSPACE_ITEM_BORDER_HIGHLIGHT_COLOR="0x90ffffff"
export WORKSPACE_ITEM_BG_COLOR="0x18ffffff"

export BAR_BG_COLOR="0x28ffffff"
export BAR_ICON_COLOR="0xff1e1e1e"
export BAR_ICON_COLOR_HIGHLIGHT="0xff2e3440"
export BAR_LABEL_COLOR="0xff1e1e1e"
export BAR_LABEL_COLOR_HIGHLIGHT="0xff2e3440"
export BAR_POPUP_BG_COLOR="0x35ffffff"
export BAR_POPUP_BORDER_COLOR="0x70ffffff"

export BATTERY_GREEN="0xffA3BE8C"
export BATTERY_YELLOW="0xffEBCB8B"
export BATTERY_RED="0xffBF616A"

export VOLUME_ICON_COLOR_RED="0xffBF616A"
export VOLUME_ICON_COLOR_ORANGE="0xffD08770"
export VOLUME_ICON_COLOR_YELLOW="0xffEBCB8B"
export VOLUME_ICON_COLOR_GREEN="0xffA3BE8C"
export VOLUME_SLIDER_HIGHLIGHT_COLOR="0xff5E81AC"
export VOLUME_SLIDER_BG_COLOR="0xff4C566A"
export VOLUME_SLIDER_KNOB_COLOR="0xffD8DEE9"

export NETWORK_NOT_CONNECTED_ICON_COLOR="0xff4C566A"
export NETWORK_WIFI_ICON_COLOR="0xff8FBCBB"
export NETWORK_VPN_ICON_COLOR="0xffA3BE8C"

export MEDIA_ICON_COLOR="0xff4C566A"
export MEDIA_ICON_PLAYING_COLOR="0xffB48EAD"
export MEDIA_LABEL_COLOR="0xffD8DEE9"

export SPOTIFY_ICON_COLOR="0xff4C566A"
export SPOTIFY_SONG_ARTIST_COLOR="0xffD8DEE9"
export SPOTIFY_SONG_ALBUM_COLOR="0xffD8DEE9"
export SPOTIFY_DURATION_COLOR="0xff4C566A"
export SPOTIFY_CONTROL_ICON_COLOR="0xff4C566A"
export SPOTIFY_CONTROL_ICON_HIGHLIGHT_COLOR="0xff88C0D0"
export SPOTIFY_CONTROL_PLAY_BG_COLOR="0xff434C5E"
export SPOTIFY_CONTROL_PLAY_BORDER_COLOR="0xff5E81AC"
export SPOTIFY_CONTROL_PLAY_ICON_COLOR="0xffD8DEE9"
export SPOTIFY_CONTROLS_BG_COLOR="0xff434C5E"

export DND_ICON_COLOR="0xffBF616A"
export DND_BORDER_COLOR="0xffBF616A"
export DND_WORK_COLOR="0xff5E81AC"
export DND_SLEEP_COLOR="0xffB48EAD"

export POMODORO_WORK_COLOR="0xffBF616A"
export POMODORO_BREAK_COLOR="0xffA3BE8C"
export POMODORO_LONG_BREAK_COLOR="0xff81A1C1"
export POMODORO_IDLE_COLOR="0xff4C566A"
export POMODORO_PAUSED_COLOR="0xffEBCB8B"

export ENABLE_WORKSPACE_ANIMATIONS="true"
export ANIMATION_DURATION_FAST="2"
export ANIMATION_DURATION_NORMAL="4"
export ANIMATION_DURATION_SLOW="6"

